### ISSUE TITLE
blender 2.82 import fails and Yup2Zup is not parented properly

### ISSUE THREAD

**Issue by jamie-pate** [godot-extended-libraries/gltf#8]
While exporting from the govox sample project from https://github.com/jamie-pate/govox
(see attached zip for a canned version)

Exporting the 'main.tscn' -> 'main.gltf2' works fine, but when importing there are errors in blender.

The platform should be a horizontal plane, but it's vertical 
![image](https://user-images.githubusercontent.com/682658/91109267-4ee98680-e62f-11ea-9a03-43dee59ddac0.png)

blender GLTF2 import:
```
Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/__init__.py", line 850, in execute
    return self.import_gltf2(context)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/__init__.py", line 864, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/__init__.py", line 887, in unit_import
    BlenderGlTF.create(self.gltf_importer)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 41, in create
    BlenderScene.create(gltf, scene_idx)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 80, in create
    BlenderNode.create(gltf, node_idx, None)  # None => No parent
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 174, in create
    BlenderNode.create(gltf, child_idx, node_idx)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 64, in create
    mesh = BlenderMesh.create(gltf, pynode.mesh, node_idx, parent)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 67, in create
    BlenderPrimitive.add_primitive_to_bmesh(gltf, bme, pymesh, prim, material_idx)
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py", line 136, in add_primitive_to_bmesh
    blender_num_components = len(bme_verts[0].link_loops[0][layer])
IndexError: BMElemSeq[index]: index 0 out of range

location: <unknown location>:-1
```
[govox-yup2zup-gltf2.zip](https://github.com/godot-extended-libraries/gltf/files/5120782/govox-yup2zup-gltf2.zip)

[system-info.txt](https://github.com/godot-extended-libraries/gltf/files/5120795/system-info.txt)

**Comment by fire** [comment]
2.82 Blender is not supported. Will close the issue after a brief reply period.

**Comment by jamie-pate** [comment]
Works in blender `2.83.5`
